### ISSUE TITLE
Cannot reproduce the segmentation in OpenNeuro dataset

### ISSUE THREAD

**Issue by 0rC0** [rockNroll87q/cerebrum7t#4]
Hi! :-)

I wanted to test this package on the dataset published on [openneuro](https://openneuro.org/datasets/ds003642/versions/1.1.0), but I cannot achieve the same results for the segmentations.

After setting the paths in the `mean_discover_BIDS.py` and `testing.py`,  I've run (using the trained model from this repository):

```
python mean_discover_BIDS.py --anat_ide '_T1w.nii.gz'
python testing.py --training_name trained_model
```

In attachment the result for `sub-025`, but also the predictions for the other two subjects are similar.

Do someone have some ideas, why I have that result?

Thanks in advance!  

[predicted.nii.gz](https://github.com/rockNroll87q/cerebrum7t/files/6519199/predicted.nii.gz)

**Comment by rockNroll87q** [comment]
Hi @0rC0,

First: thanks for trying the method! Really appreciated! :) 

About the testing, the code in `mean_discover_BIDS.py` should be used only when a training or fine-tuning is needed. Our fault that we didn't specify that and, most importantly, didn't share the `mean` and `std` volumes for the testing. Technically, you can obtain them using the [code](https://github.com/rockNroll87q/cerebrum7t/blob/master/src/misc/mean_discover_BIDS.py) that you used on the shared db [here](https://search.kg.ebrains.eu/instances/Dataset/2b24466d-f1cd-4b66-afa8-d70a6755ebea). But it's a waste of time: let me share those volumes with you.

You can download the files [at this link](https://cloud.psy.gla.ac.uk/index.php/s/efPCRdOB6FCEzrT) (psw: `rocknroll87q/cerebrum7t`).
We are updating the [Usage](https://rocknroll87q.github.io/cerebrum7t/usage) page to reflect that.

**Comment by 0rC0** [comment]
Hi @rockNroll87q,

thank you very much for sharing the files (and the code :-) ). 

Now it works very good and I can reproduce the results! 

I'm going to try it on some mp2rage data I work with. I close the Issue because is solved.

Best wishes
Andrea
