### ISSUE TITLE
Typo found in offline_data_augmentation.py

### ISSUE THREAD

**Issue by ChengranAA** [rockNroll87q/cerebrum7t#7]
From Line 194 "# If the augmented GT or T1 is not created, then re-run the function" 
But Line 195  "if not os.path.exists(gt_augm_fullpath) or not os.path.exists(gt_augm_fullpath):"

Only Ground truth path is checked, I guess there is a small typo in this code. 
If it is I can make a pull request and fix this small error. 

Cheers.

**Comment by rockNroll87q** [comment]
Hi @ChengranAA , yes, you are right. If you have time, yes please make a pull request. Thank you!
