### ISSUE TITLE
Issue with change GT volume to one-hot encoding. 

### ISSUE THREAD

**Issue by ChengranAA** [rockNroll87q/cerebrum7t#9]
I had an issue when runing the fine tuning script, I have localized the problem to the function `to_categorical()` in volume_manager.py, this function only works with labels that starts with 0 and incremented sequentially, for example, my data has the label `[0, 50, 100]`, so it will not work with the `to_categorical()` function. 

What I think might fix this issue is to factorrize the array first before categorize it. 
I added this function to the `loadDatasetFromListFiles` function. 

```
def encode_np_array_to_factors(arr):
    unique_values = np.unique(arr)
    factor_mapping = {value: index for index, value in enumerate(unique_values)}
    encoded_factors = np.vectorize(factor_mapping.get)(arr)
    return encoded_factors
```

and changed this line 
```
i_GT_loaded = to_categorical_tensor(i_GT_loaded, num_segmask_labels).astype(dtype='uint8')
```
to this 
```
i_GT_loaded = to_categorical_tensor(encode_np_array_to_factors(i_GT_loaded), num_segmask_labels).astype(dtype='uint8')
```

this way it is able to handle GT_volume with labels that are not sequentially incremented (from `[0, 50, 100]` to `[0, 1, 2]`). 

I don't know if you prefer this way, or if it is better to add in the instruction to indicate that the GT_volume needs to be sequentially incremented.

**Comment by rockNroll87q** [comment]
Hi @ChengranAA , you are right, indeed. It works only with sequential labelling. Thanks a lot for the fix; I'll keep your post so that people will have a solution if needed and I added a note in the instructions. Best
